name: Threadfin Beta Build
on:
  push:
    tags:
      - BETA-*
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: Get dependencies
        run: |
          go mod download

      - name: Build
        uses: izumin5210/action-go-crossbuild@v1.0.0

      - name: Pre-Release
        uses: softprops/action-gh-release@v0.1.13
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
          prerelease: true
